global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Embedding Server
  - job_name: 'embedding-server'
    static_configs:
      - targets: ['embedding-server:8003']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Main Backend
  - job_name: 'main-backend'
    static_configs:
      - targets: ['main-backend:8000']
    metrics_path: '/health'
    scrape_interval: 30s

  # MCP Server
  - job_name: 'mcp-server'
    static_configs:
      - targets: ['mcp-server:8002']
    metrics_path: '/health'
    scrape_interval: 30s

  # LLM Agent
  - job_name: 'llm-agent'
    static_configs:
      - targets: ['llm-agent-openai:8001']
    metrics_path: '/health'
    scrape_interval: 30s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  # Embedding PostgreSQL
  - job_name: 'embedding-postgres'
    static_configs:
      - targets: ['embedding-postgres:5432']
    scrape_interval: 30s
